name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Build on ${{ matrix.os }}
      run: cargo build --verbose
    - name: Run tests on ${{ matrix.os }}
      run: cargo test --verbose
    - name: Run clippy lints
      run: cargo clippy --verbose --no-deps
    - name: Validate formatting
      run: cargo fmt --all -- --check
